services:
  - type: web
    name: chatesp-2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120
    envVars:
      - key: AI_API_KEY
        sync: false
      - key: AI_URL
        value: https://api.groq.com/openai/v1/chat/completions
      - key: AI_MODEL
        value: openai/gpt-oss-20b
      - key: WHISPER_MODEL
        value: base
      - key: WHISPER_DEVICE
        value: cpu
      - key: WHISPER_COMPUTE
        value: int8
